spring.application.name=auth-service

server.port=8081

spring.datasource.url=jdbc:postgresql://localhost:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=jwt.secret=7f4d8c0c9e8f4f51a6e4d2a9f6b3c1e7a8d9b2c4e6f1a3b5c7d9e2f4a6b8c0
jwt.expiration=86400000